package GUI;
import java.awt.FileDialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;

import javax.swing.JOptionPane;

import Backend.Properties;
import Main.Main;

/**
 *
 * @author James
 */
public class ConfigTechReviewDialog extends javax.swing.JDialog {

	Properties prop = Properties.getInstance();
	/**
	 * Creates new form ConfigTechReviewDialog
	 */
	public ConfigTechReviewDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();

		this.addWindowListener((WindowListener) new WindowAdapter() {

			@Override
			public void windowClosing(WindowEvent arg0) {
				dispose();
			}

		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		String[] currentValues = prop.getTechReviewSettings();

		saveBtn = new javax.swing.JButton();
		cancelBtn = new javax.swing.JButton();
		session1ReviewJlabel = new javax.swing.JLabel();
		session1ReviewTextField = new javax.swing.JTextField();
		session1ReviewBrowseBtn = new javax.swing.JButton();
		session2ReviewJlabel = new javax.swing.JLabel();
		session2ReviewTextField = new javax.swing.JTextField();
		session2ReviewBrowseBtn = new javax.swing.JButton();
		session3ReviewJlabel = new javax.swing.JLabel();
		session3ReviewTextField = new javax.swing.JTextField();
		session3ReviewBrowseBtn = new javax.swing.JButton();
		session4ReviewJlabel = new javax.swing.JLabel();
		session4ReviewTextField = new javax.swing.JTextField();
		session4ReviewBrowseBtn = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		saveBtn.setText("Save");
		saveBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveBtnActionPerformed(evt);
			}
		});

		cancelBtn.setText("Cancel");
		cancelBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelBtnActionPerformed(evt);
			}
		});

		session1ReviewJlabel.setText("<html>Session 1 Tech\nReview PDF File: ");

		session1ReviewTextField.setText(currentValues[0]);

		session1ReviewBrowseBtn.setText("Browse");
		session1ReviewBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				session1ReviewBrowseBtnActionPerformed(evt);
			}
		});

		session2ReviewJlabel.setText("<html>Session 2 Tech Review PDF File: ");

		session2ReviewTextField.setText(currentValues[1]);

		session2ReviewBrowseBtn.setText("Browse");
		session2ReviewBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				session2ReviewBrowseBtnActionPerformed(evt);
			}
		});

		session3ReviewJlabel.setText("<html>Session 3 Tech Review PDF File: ");

		session3ReviewTextField.setText(currentValues[2]);

		session3ReviewBrowseBtn.setText("Browse");
		session3ReviewBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				session3ReviewBrowseBtnActionPerformed(evt);
			}
		});

		session4ReviewJlabel.setText("<html>Session 4 Tech Review PDF File: ");

		session4ReviewTextField.setText(currentValues[3]);

		session4ReviewBrowseBtn.setText("Browse");
		session4ReviewBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				session4ReviewBrowseBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(session4ReviewJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(session4ReviewTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup()
										.addComponent(session3ReviewJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(session3ReviewTextField))
								.addGroup(layout.createSequentialGroup()
										.addComponent(session1ReviewJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(session1ReviewTextField))
								.addGroup(layout.createSequentialGroup()
										.addComponent(session2ReviewJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(session2ReviewTextField)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(session3ReviewBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
								.addComponent(session2ReviewBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(session4ReviewBrowseBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(session1ReviewBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(18, 18, 18))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(65, 65, 65)
						.addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(298, 298, 298))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(session1ReviewJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(session1ReviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(session1ReviewBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(session2ReviewJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(session2ReviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(session2ReviewBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(session3ReviewJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(session3ReviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(session3ReviewBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(session4ReviewJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(session4ReviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(session4ReviewBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>                        

	private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
		String[] values = new String[4];
		values[0] = session1ReviewTextField.getText();
		values[1] = session2ReviewTextField.getText();
		values[2] = session3ReviewTextField.getText();
		values[3] = session4ReviewTextField.getText();

		prop.saveTechReviewsPDF(values);
		JOptionPane.showMessageDialog(this,
				"Settings changed!");

		this.dispose();

	}                                       

	private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
		dispose();
	}                                         

	private void session1ReviewBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                        

		String browseResult = browseFiles();
		if (browseResult != null) {
			session1ReviewTextField.setText(browseResult);
		}    }                                                       

	private void session2ReviewBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                        
		String browseResult = browseFiles();
		if (browseResult != null) {
			session2ReviewTextField.setText(browseResult);
		}   
	}                                                                 

	private void session3ReviewBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                        
		String browseResult = browseFiles();
		if (browseResult != null) {
			session3ReviewTextField.setText(browseResult);
		}    
	}                                                                 

	private void session4ReviewBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                        
		String browseResult = browseFiles();
		if (browseResult != null) {
			session4ReviewTextField.setText(browseResult);
		}    
	}                                                                

	// Variables declaration - do not modify                     
	private javax.swing.JButton cancelBtn;
	private javax.swing.JButton saveBtn;
	private javax.swing.JButton session1ReviewBrowseBtn;
	private javax.swing.JLabel session1ReviewJlabel;
	private javax.swing.JTextField session1ReviewTextField;
	private javax.swing.JButton session2ReviewBrowseBtn;
	private javax.swing.JLabel session2ReviewJlabel;
	private javax.swing.JTextField session2ReviewTextField;
	private javax.swing.JButton session3ReviewBrowseBtn;
	private javax.swing.JLabel session3ReviewJlabel;
	private javax.swing.JTextField session3ReviewTextField;
	private javax.swing.JButton session4ReviewBrowseBtn;
	private javax.swing.JLabel session4ReviewJlabel;
	private javax.swing.JTextField session4ReviewTextField;
	// End of variables declaration    


	public String browseFiles() {
		FileDialog fd = new FileDialog(this, "Open", FileDialog.LOAD); 
		fd.show();    	

		if (fd.getFile() == null) {
			return null;
		}

		else {
			String fileName = new File(fd.getFile()).getName();
			String directory = fd.getDirectory();
			return (directory + fileName);

		}


	}
}

