package GUI;
import java.awt.FileDialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import Backend.Main;
import Backend.Properties;

/**
 *
 * @author James
 */
public class ConfigTechReviewDialog extends javax.swing.JDialog {

	Properties prop = Properties.getInstance();
	/**
	 * Creates new form ConfigTechReviewDialog
	 */
	public ConfigTechReviewDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();

		this.addWindowListener((WindowListener) new WindowAdapter() {

			@Override
			public void windowClosing(WindowEvent arg0) {
				dispose();
			}

		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		String[] currentValues = prop.getTechReviewSettings();

		saveBtn = new javax.swing.JButton();
		cancelBtn = new javax.swing.JButton();
		session1ReviewJlabel = new javax.swing.JLabel();
		session1ReviewTextField = new javax.swing.JTextField();
		session1ReviewBrowseBtn = new javax.swing.JButton();
		session2ReviewJlabel = new javax.swing.JLabel();
		session2ReviewTextField = new javax.swing.JTextField();
		session2ReviewBrowseBtn = new javax.swing.JButton();
		session3ReviewJlabel = new javax.swing.JLabel();
		session3ReviewTextField = new javax.swing.JTextField();
		session3ReviewBrowseBtn = new javax.swing.JButton();
		session4ReviewJlabel = new javax.swing.JLabel();
		session4ReviewTextField = new javax.swing.JTextField();
		session4ReviewBrowseBtn = new javax.swing.JButton();
		rootSaveLocationJlabel = new javax.swing.JLabel();
		rootSaveLocationTextField = new javax.swing.JTextField();
		rootSaveLocationBrowseBtn = new javax.swing.JButton();
		

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		saveBtn.setText("Save");
		saveBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveBtnActionPerformed(evt);
			}
		});

		cancelBtn.setText("Cancel");
		cancelBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelBtnActionPerformed(evt);
			}
		});

		session1ReviewJlabel.setText("<html>Session 1 Tech\nReview PDF File: ");

		session1ReviewTextField.setText(currentValues[0]);

		session1ReviewBrowseBtn.setText("Browse");
		session1ReviewBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				session1ReviewBrowseBtnActionPerformed(evt);
			}
		});

		session2ReviewJlabel.setText("<html>Session 2 Tech Review PDF File: ");

		session2ReviewTextField.setText(currentValues[1]);

		session2ReviewBrowseBtn.setText("Browse");
		session2ReviewBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				session2ReviewBrowseBtnActionPerformed(evt);
			}
		});

		session3ReviewJlabel.setText("<html>Session 3 Tech Review PDF File: ");

		session3ReviewTextField.setText(currentValues[2]);

		session3ReviewBrowseBtn.setText("Browse");
		session3ReviewBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				session3ReviewBrowseBtnActionPerformed(evt);
			}
		});

		session4ReviewJlabel.setText("<html>Session 4 Tech Review PDF File: ");

		session4ReviewTextField.setText(currentValues[3]);

		session4ReviewBrowseBtn.setText("Browse");
		session4ReviewBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				session4ReviewBrowseBtnActionPerformed(evt);
			}
		});
		

        rootSaveLocationJlabel.setText("Root save directory location: ");

        rootSaveLocationTextField.setText(currentValues[4]);

        rootSaveLocationBrowseBtn.setText("Browse");
        rootSaveLocationBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootSaveLocationBrowseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(session4ReviewJlabel)
                                .addGap(18, 18, 18)
                                .addComponent(session4ReviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rootSaveLocationJlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rootSaveLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(session4ReviewBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(rootSaveLocationBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(session3ReviewJlabel)
                                .addGap(18, 18, 18)
                                .addComponent(session3ReviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(session1ReviewJlabel)
                                .addGap(18, 18, 18)
                                .addComponent(session1ReviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(session2ReviewJlabel)
                                .addGap(18, 18, 18)
                                .addComponent(session2ReviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(session1ReviewBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(session2ReviewBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(session3ReviewBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(session1ReviewBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(session1ReviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(session1ReviewJlabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(session2ReviewJlabel)
                    .addComponent(session2ReviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(session2ReviewBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(session3ReviewJlabel)
                    .addComponent(session3ReviewBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(session3ReviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(session4ReviewBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(session4ReviewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(session4ReviewJlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rootSaveLocationJlabel)
                    .addComponent(rootSaveLocationBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rootSaveLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
	}// </editor-fold>                        

	private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
		String[] values = new String[5];
		values[0] = session1ReviewTextField.getText();
		values[1] = session2ReviewTextField.getText();
		values[2] = session3ReviewTextField.getText();
		values[3] = session4ReviewTextField.getText();
		values[4] = rootSaveLocationTextField.getText();


		prop.saveTechReviewsPDF(values);
		JOptionPane.showMessageDialog(this,
				"Settings changed!");

		this.dispose();

	}                                       

	private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
		dispose();
	}                                         

	private void session1ReviewBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                        

		String browseResult = browseFiles();
		if (browseResult != null) {
			session1ReviewTextField.setText(browseResult);
		}    }                                                       

	private void session2ReviewBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                        
		String browseResult = browseFiles();
		if (browseResult != null) {
			session2ReviewTextField.setText(browseResult);
		}   
	}                                                                 

	private void session3ReviewBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                        
		String browseResult = browseFiles();
		if (browseResult != null) {
			session3ReviewTextField.setText(browseResult);
		}    
	}                                                                 

	private void session4ReviewBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                        
		String browseResult = browseFiles();
		if (browseResult != null) {
			session4ReviewTextField.setText(browseResult);
		}    
	}           
	
	private void rootSaveLocationBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                        
		String browseResult = browseFolder();
		if (browseResult != null) {
			rootSaveLocationTextField.setText(browseResult);
		}    
	}      

	// Variables declaration - do not modify                     
	private javax.swing.JButton cancelBtn;
	private javax.swing.JButton saveBtn;
	private javax.swing.JButton session1ReviewBrowseBtn;
	private javax.swing.JLabel session1ReviewJlabel;
	private javax.swing.JTextField session1ReviewTextField;
	private javax.swing.JButton session2ReviewBrowseBtn;
	private javax.swing.JLabel session2ReviewJlabel;
	private javax.swing.JTextField session2ReviewTextField;
	private javax.swing.JButton session3ReviewBrowseBtn;
	private javax.swing.JLabel session3ReviewJlabel;
	private javax.swing.JTextField session3ReviewTextField;
	private javax.swing.JButton session4ReviewBrowseBtn;
	private javax.swing.JLabel session4ReviewJlabel;
	private javax.swing.JTextField session4ReviewTextField;
	private javax.swing.JButton rootSaveLocationBrowseBtn;
	private javax.swing.JLabel rootSaveLocationJlabel;
	private javax.swing.JTextField rootSaveLocationTextField;
	// End of variables declaration    


	public String browseFiles() {
		FileDialog fd = new FileDialog(this, "Open", FileDialog.LOAD); 
		fd.show();    	

		if (fd.getFile() == null) {
			return null;
		}

		else {
			String fileName = new File(fd.getFile()).getName();
			String directory = fd.getDirectory();
			return (directory + fileName);

		}


	}
	
	
	public String browseFolder() {
		
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY);
        //jFileChooser.setCurrentDirectory(new File("/User/alvinreyes"));
         
        int result = jFileChooser.showOpenDialog(new JFrame());
     
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jFileChooser.getSelectedFile();
            return selectedFile.getAbsolutePath();
        }
        
        return null;


	}
}

