package GUI;
import java.awt.FileDialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import Backend.Main;
import Backend.Properties;

public class ConfigTrainerInfoDialog extends javax.swing.JDialog  {

		Properties prop = Properties.getInstance();
		
	    /**
	     * Creates new form ConfigTrainerInfoDialog
	     */
	    public ConfigTrainerInfoDialog(java.awt.Frame parent, boolean modal) {
	        super(parent, modal);
	        initComponents();
	        
	        this.addWindowListener((WindowListener) new WindowAdapter() {

	            @Override
	            public void windowClosing(WindowEvent arg0) {
	            	dispose();

	            }

	        });
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        trainerNameJlabel = new javax.swing.JLabel();
	        trainerNameTextField = new javax.swing.JTextField();
	        cancelBtn = new javax.swing.JButton();
	        saveBtn = new javax.swing.JButton();
	        trainerNumberJlabel = new javax.swing.JLabel();
	        trainerNumberTextField = new javax.swing.JTextField();

	        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

	        String currentTrainerInfo[] = prop.getTrainerInfo();
	        
	        trainerNameJlabel.setText("Your name as a trainer:");

	        trainerNameTextField.setText(currentTrainerInfo[0]);

	        cancelBtn.setText("Cancel");
	        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                cancelBtnActionPerformed(evt);
	            }
	        });

	        saveBtn.setText("Save");
	        saveBtn.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                saveBtnActionPerformed(evt);
	            }
	        });

	        trainerNumberJlabel.setText("Your phone extention number:");

	        trainerNumberTextField.setText(currentTrainerInfo[1]);


	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addContainerGap(303, Short.MAX_VALUE)
	                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(65, 65, 65)
	                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(298, 298, 298))
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(trainerNameJlabel)
	                    .addComponent(trainerNumberJlabel))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(trainerNameTextField)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(trainerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(trainerNumberTextField)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(trainerNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addGap(22, 22, 22))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(trainerNameJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(trainerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(trainerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(trainerNumberJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(trainerNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(trainerNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap())
	        );

	        pack();
	    }// </editor-fold>                        
                                             

	    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
	    	dispose();
	    }                                         

	    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
			String[] values = new String[2];
			values[0] = trainerNameTextField.getText();
			values[1] = trainerNumberTextField.getText();

			prop.saveTrainerInfo(values);
			JOptionPane.showMessageDialog(this,
					"Settings changed!");

			dispose();
	    }                                       
                                   


	    // Variables declaration - do not modify                     
	    private javax.swing.JButton cancelBtn;
	    private javax.swing.JLabel trainerNumberJlabel;
	    private javax.swing.JTextField trainerNumberTextField;
	    private javax.swing.JButton saveBtn;
	    private javax.swing.JLabel trainerNameJlabel;
	    private javax.swing.JTextField trainerNameTextField;
	    // End of variables declaration                   
	    
		
	
}




