import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

import javax.swing.JOptionPane;

/**
 *
 * @author James
 */
public class ConfigDoorSignDialog extends javax.swing.JDialog {
	
	Properties prop = Properties.getInstance();
	private Frame parentFrame;

    public ConfigDoorSignDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        parentFrame = parent;
        initComponents();
        
        this.addWindowListener((WindowListener) new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent arg0) {
            	parent.dispose();
                Main.main(null);
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        doorSignJLabel = new javax.swing.JLabel();
        doorSignTextField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        doorSignBrowseBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        session1DescriptionJlabel = new javax.swing.JLabel();
        session1DescriptionTextField = new javax.swing.JTextField();
        session1DescriptionBrowseBtn = new javax.swing.JButton();
        session2DescriptionJlabel = new javax.swing.JLabel();
        session2DescriptionTextField = new javax.swing.JTextField();
        session2DescriptionBrowseBtn = new javax.swing.JButton();
        session3DescriptionJlabel = new javax.swing.JLabel();
        session3DescriptionTextField = new javax.swing.JTextField();
        session3DescriptionBrowseBtn = new javax.swing.JButton();
        session4DescriptionJlabel = new javax.swing.JLabel();
        session4DescriptionTextField = new javax.swing.JTextField();
        session4DescriptionBrowseBtn = new javax.swing.JButton();
        trainingRoomsJlabel = new javax.swing.JLabel();
        trainingRoomsTextField = new javax.swing.JTextField();
        trainingRoomsBrowseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        doorSignJLabel.setText("Door Sign PDF File:");

        doorSignTextField.setText("jTextField1");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        doorSignBrowseBtn.setText("Browse");
        doorSignBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doorSignBrowseBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        session1DescriptionJlabel.setText("Session 1 Description:");

        session1DescriptionTextField.setText("jTextField1");

        session1DescriptionBrowseBtn.setText("Browse");
        session1DescriptionBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                session1DescriptionBrowseBtnActionPerformed(evt);
            }
        });

        session2DescriptionJlabel.setText("Session 2 Description:");

        session2DescriptionTextField.setText("jTextField1");

        session2DescriptionBrowseBtn.setText("Browse");
        session2DescriptionBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                session2DescriptionBrowseBtnActionPerformed(evt);
            }
        });

        session3DescriptionJlabel.setText("Session 3 Description:");

        session3DescriptionTextField.setText("jTextField1");

        session3DescriptionBrowseBtn.setText("Browse");
        session3DescriptionBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                session3DescriptionBrowseBtnActionPerformed(evt);
            }
        });

        session4DescriptionJlabel.setText("Session 4 Description:");

        session4DescriptionTextField.setText("jTextField1");

        session4DescriptionBrowseBtn.setText("Browse");
        session4DescriptionBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                session4DescriptionBrowseBtnActionPerformed(evt);
            }
        });

        trainingRoomsJlabel.setText("Training Rooms:");

        trainingRoomsTextField.setText("jTextField1");

        trainingRoomsBrowseBtn.setText("Browse");
        trainingRoomsBrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainingRoomsBrowseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainingRoomsJlabel)
                    .addComponent(session4DescriptionJlabel)
                    .addComponent(session3DescriptionJlabel)
                    .addComponent(session2DescriptionJlabel)
                    .addComponent(session1DescriptionJlabel)
                    .addComponent(doorSignJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(doorSignTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(session1DescriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                        .addComponent(session2DescriptionTextField)
                        .addComponent(session3DescriptionTextField)
                        .addComponent(session4DescriptionTextField)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(94, 94, 94)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(157, 157, 157))
                        .addComponent(trainingRoomsTextField)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(doorSignBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(session1DescriptionBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(session2DescriptionBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(session3DescriptionBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(session4DescriptionBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trainingRoomsBrowseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doorSignJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doorSignTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doorSignBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(session1DescriptionJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(session1DescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(session1DescriptionBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(session2DescriptionJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(session2DescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(session2DescriptionBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(session3DescriptionJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(session3DescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(session3DescriptionBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(session4DescriptionJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(session4DescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(session4DescriptionBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trainingRoomsJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trainingRoomsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trainingRoomsBrowseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>                        

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	prop.saveScheduleFileName(fileLocationTxtField.getText());
    	JOptionPane.showMessageDialog(this,
    		    "Settings changed!",
    		    JOptionPane.PLAIN_MESSAGE);
    	
    	parentFrame.dispose();
    	
    	Main.main(null);
    }                                       

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
    	parentFrame.dispose();
   		Main.main(null);

    }                                              

    private void doorSignBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void session1DescriptionBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
    }                                                            

    private void session2DescriptionBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
    }                                                            

    private void session3DescriptionBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
    }                                                            

    private void session4DescriptionBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
    }                                                            

    private void trainingRoomsBrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    // Variables declaration - do not modify                     
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton doorSignBrowseBtn;
    private javax.swing.JLabel doorSignJLabel;
    private javax.swing.JTextField doorSignTextField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton session1DescriptionBrowseBtn;
    private javax.swing.JLabel session1DescriptionJlabel;
    private javax.swing.JTextField session1DescriptionTextField;
    private javax.swing.JButton session2DescriptionBrowseBtn;
    private javax.swing.JLabel session2DescriptionJlabel;
    private javax.swing.JTextField session2DescriptionTextField;
    private javax.swing.JButton session3DescriptionBrowseBtn;
    private javax.swing.JLabel session3DescriptionJlabel;
    private javax.swing.JTextField session3DescriptionTextField;
    private javax.swing.JButton session4DescriptionBrowseBtn;
    private javax.swing.JLabel session4DescriptionJlabel;
    private javax.swing.JTextField session4DescriptionTextField;
    private javax.swing.JButton trainingRoomsBrowseBtn;
    private javax.swing.JLabel trainingRoomsJlabel;
    private javax.swing.JTextField trainingRoomsTextField;
    // End of variables declaration                   
}
